# This file was generated by GoReleaser. DO NOT EDIT.
cask "betterleaks" do
  name "betterleaks"
  desc "Secrets scanner built on the legacy of gitleaks"
  homepage "https://github.com/betterleaks/betterleaks"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "betterleaks"

  on_macos do
    on_intel do
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_darwin_x64.tar.gz"
      sha256 "9462919fc8b625cc86f5ca216a0ca8366b1492c795f2a52710338e38875078f4"
    end
    on_arm do
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_darwin_arm64.tar.gz"
      sha256 "81eb78a8328f9159421855f282a03ad40c2cfeaa7c7a79f4c42308d705be31c4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_linux_x64.tar.gz"
      sha256 "d590d5f051e49f6769c61dc8cebbce947b20a4042e2915ee234760f81a01c8c4"
    end
    on_arm do
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_linux_arm64.tar.gz"
      sha256 "97b774367630846a5f2298f7f3e3f8096f0567d3fc0275b1b63c0e1e16f856f1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/betterleaks"]
    end
  end

  # No zap stanza required
end
