# This file was generated by GoReleaser. DO NOT EDIT.
cask "betterleaks" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "bbbbf362ddd0a0c5d37633707206be92501ba5f3291ea45af0c6ab3980ec693d"
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_darwin_x64.tar.gz"
    end
    on_arm do
      sha256 "a341e534f152bd10fa8309d74e2ab7eadb634f16ddeb7c3f43ca54f8a016905b"
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b883e8c61a3a14c90ff46a08c203cf88fe340ed88251d4c049db5530ec0ac54b"
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_linux_x64.tar.gz"
    end
    on_arm do
      sha256 "f4e89eccde1cdf0cf048748876757e56705d21f122fa4284a4b84803da288608"
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_linux_arm64.tar.gz"
    end
  end

  name "betterleaks"
  desc "Secrets scanner built on the legacy of gitleaks"
  homepage "https://github.com/betterleaks/betterleaks"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "betterleaks"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/betterleaks"]
    end
  end

  # No zap stanza required

end
