# This file was generated by GoReleaser. DO NOT EDIT.
cask "betterleaks@1" do
  version "1.9.0"

  on_macos do
    on_arm do
      sha256 "83dd7eaab13d44a1e8e347a17064cdef153a1478db473276d41b38d55613d3f2"
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "68dfd83458d9e7f90663daa7a81c7f944083b170dae82e4f5f8d0581ed519ef1"
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_darwin_x64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1d39116e0a58dc94574715e2aa12a2dbd5062f193eee3fec011fef6ba06bd13b"
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f8b185a39ffcece2a1ca82bf3a4e7435cd81963ffd16b7a9128daf75f35f6de7"
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_linux_x64.tar.gz"
    end
  end

  name "betterleaks@1"
  desc "Secrets scanner built on the legacy of gitleaks"
  homepage "https://github.com/betterleaks/betterleaks"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "betterleaks", target: "betterleaks-v1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/betterleaks"]
    end
  end

  # No zap stanza required
end
