# This file was generated by GoReleaser. DO NOT EDIT.
cask "betterleaks" do
  version "1.7.1"

  on_macos do
    on_intel do
      sha256 "cdec2e001513019c4bb18dbb2982c472b5e7dc4fab053cf7b7814ef94aee7eea"
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_darwin_x64.tar.gz"
    end
    on_arm do
      sha256 "2c75082322bacc78763a725326b1bf7f013a2e46ac5696786b2c0bf49e545a34"
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "48d9ae267b46677c9943cf9291bed682ed7b37b5b2c6ffbdea47a155495e5dcc"
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_linux_x64.tar.gz"
    end
    on_arm do
      sha256 "c350f1c94c7187f81a8900aa17b50ee868fdc72e89dac849d68d757754665721"
      url "https://github.com/betterleaks/betterleaks/releases/download/v#{version}/betterleaks_#{version}_linux_arm64.tar.gz"
    end
  end

  name "betterleaks"
  desc "Secrets scanner built on the legacy of gitleaks"
  homepage "https://github.com/betterleaks/betterleaks"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "betterleaks"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/betterleaks"]
    end
  end

  # No zap stanza required

end
